// Types
import type { NextPage } from 'next'

// Next
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='bg-gray-900 mb-4 py-2'>
        <div className='container'>
          <p className='text-white'>SHD Builder</p>
        </div>
      </div>

      <div className='container border p-4 rounded'>
        <p className='font-bold'>Welcome to the SHD Builder.</p>
        <p>If you are an administrator, please sign in here:</p>
      </div>
    </div>
  )
}

export default Home
