// Types
import type { NextPage } from 'next'

// Next
import Head from 'next/head'
import Link from 'next/link'

// Context
import { useAuthContext } from '@/context/auth'

const Home: NextPage = () => {
  const { user } = useAuthContext()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='container border p-4 rounded'>
        <p className='font-bold'>Welcome to the SHD Builder.</p>
        {!user && (
          <>
            <Link href='/register'>
              <a>Register</a>
            </Link>
            <Link href='/login'>
              <a>Login</a>
            </Link>
          </>
        )}
      </div>
    </>
  )
}

export default Home
