// Types
import type { NextPage } from 'next'

// Hooks
import { useEffect } from 'react'

// Next
import Head from 'next/head'
import { useRouter } from 'next/router'

// Context
import { useAuthContext } from '../context/auth'

// Components
import RegisterForm from '../components/RegisterForm'

const Register: NextPage = () => {
  const router = useRouter()

  const { user } = useAuthContext()

  useEffect(() => {
    if (user) {
      router.push('/')
    }
  }, [router, user])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='container border p-4 rounded'>
        <p className='font-bold'>Register to the SHD Builder.</p>
        <RegisterForm />
      </div>
    </div>
  )
}

export default Register
